<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>CybersecurityChatbot</RootNamespace>
		<AssemblyName>CybersecurityChatbot</AssemblyName>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<!-- MySQL database package -->
	<ItemGroup>
		<PackageReference Include="MySql.Data" Version="8.3.0"/>
	</ItemGroup>

	<ItemGroup>
		<None Update="Resources\greeting.wav">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>